# Generated by Django 5.2.16 on 2026-07-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_lead_detail_360'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='auto_assign_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, unassigned leads are given to the next agent in round-robin order.'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='round_robin_cursor',
            field=models.PositiveIntegerField(default=0, help_text='Index into the org agent list for the next auto-assignment.'),
        ),
    ]
