# Generated by Django 5.2.16 on 2026-07-10 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_assignment_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('static', 'Static list'), ('segment', 'Dynamic segment')], default='static', max_length=16)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lists', to='leads.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactListMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='leads.contactlist')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to='leads.lead')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contactlist',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='uniq_contact_list_org_name'),
        ),
        migrations.AddConstraint(
            model_name='contactlistmembership',
            constraint=models.UniqueConstraint(fields=('contact_list', 'lead'), name='uniq_contact_list_lead'),
        ),
    ]
