# Generated by Django 5.2.16 on 2026-07-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_contact_lists_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='physical_address',
            field=models.TextField(blank=True, default='', help_text='Postal address shown in marketing email footers (CAN-SPAM).'),
        ),
    ]
