# Generated by Django 5.2.16 on 2026-07-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_email_tracking_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_emailed_at',
            field=models.DateTimeField(blank=True, help_text='When the lead was last sent a marketing/transactional email.', null=True),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='kind',
            field=models.CharField(choices=[('note', 'Note'), ('task_created', 'Task created'), ('task_completed', 'Task completed'), ('status', 'Status change'), ('assignment', 'Assignment'), ('custom', 'Custom field'), ('email_sent', 'Email sent'), ('email_open', 'Email opened'), ('email_click', 'Email clicked'), ('email_unsubscribe', 'Unsubscribed')], max_length=32),
        ),
    ]
