# Generated by Django 5.2.16 on 2026-07-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_lead_email_activity_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
