# Generated by Django 5.2.16 on 2026-07-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_stripe_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='from_email',
            field=models.EmailField(blank=True, default='', help_text='Optional org From address; falls back to the platform default.', max_length=254),
        ),
        migrations.AddField(
            model_name='organisation',
            name='from_name',
            field=models.CharField(blank=True, default='', help_text='Display name used in outbound From headers.', max_length=120),
        ),
    ]
