# Generated by Django 5.2.16 on 2026-07-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_org_email_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='onboarding_dismissed_at',
            field=models.DateTimeField(blank=True, help_text='When set, the onboarding checklist is hidden for this org.', null=True),
        ),
    ]
