# Generated by Django 5.2.16 on 2026-07-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_onboarding_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
