# Generated by Django 5.2.16 on 2026-07-10 22:28

import capture.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_engine', '0006_outbound_quota_status'),
        ('leads', '0023_onboarding_dismissed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCaptureForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('public_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fields_config', models.JSONField(blank=True, default=capture.models.default_fields_config)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_forms', to='email_engine.emailsequence')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_forms', to='leads.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'name'), name='uniq_capture_form_org_name')],
            },
        ),
    ]
