# Generated by Django 5.2.16 on 2026-07-10 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_engine', '0001_email_provider_integration'),
        ('leads', '0018_contact_lists_segments'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(help_text='HTML body. Use merge tags like {{first_name}}.')),
                ('body_text', models.TextField(blank=True, help_text='Optional plain-text fallback.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='leads.organisation')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'name'), name='uniq_email_template_org_name')],
            },
        ),
    ]
