# Generated by Django 5.2.16 on 2026-07-10 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_engine', '0003_campaigns_one_shot'),
        ('leads', '0018_contact_lists_segments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('exit_on_reply', models.BooleanField(default=True)),
                ('exit_on_stage_change', models.BooleanField(default=True)),
                ('exit_on_unsubscribe', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sequences', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sequences', to='leads.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(blank=True, default='unsubscribe', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_suppressions', to='leads.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('exited', 'Exited'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('current_step_position', models.PositiveIntegerField(default=0)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, choices=[('completed', 'Completed'), ('reply', 'Reply'), ('stage_change', 'Stage change'), ('unsubscribe', 'Unsubscribe'), ('manual', 'Manual'), ('cancelled', 'Cancelled')], max_length=32)),
                ('enrolled_category_id', models.IntegerField(blank=True, null=True)),
                ('reply_detected_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_enrollments', to='leads.lead')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='email_engine.emailsequence')),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('delay_days', models.PositiveIntegerField(default=0, help_text='Wait this many days after the previous step (or enrollment).')),
                ('delay_hours', models.PositiveIntegerField(default=0, help_text='Additional hours of delay (useful for testing).')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='email_engine.emailsequence')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequence_steps', to='email_engine.emailtemplate')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SequenceStepSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='email_engine.sequenceenrollment')),
                ('outbound_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequence_sends', to='email_engine.outboundemail')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='email_engine.sequencestep')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='emailsequence',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='uniq_email_sequence_org_name'),
        ),
        migrations.AddConstraint(
            model_name='emailsuppression',
            constraint=models.UniqueConstraint(fields=('organisation', 'email'), name='uniq_email_suppression_org_email'),
        ),
        migrations.AddConstraint(
            model_name='sequenceenrollment',
            constraint=models.UniqueConstraint(fields=('sequence', 'lead'), name='uniq_sequence_lead_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='sequencestep',
            constraint=models.UniqueConstraint(fields=('sequence', 'position'), name='uniq_sequence_step_position'),
        ),
        migrations.AddConstraint(
            model_name='sequencestepsend',
            constraint=models.UniqueConstraint(fields=('enrollment', 'step'), name='uniq_enrollment_step_send'),
        ),
    ]
