# Generated by Django 5.2.16 on 2026-07-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_engine', '0004_campaign_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundemail',
            name='tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outboundemail',
            name='tracking_token',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emaildeliveryevent',
            name='event_type',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('open', 'Open'), ('click', 'Click'), ('failed', 'Failed'), ('unsubscribe', 'Unsubscribe')], max_length=32),
        ),
        migrations.AlterField(
            model_name='outboundemail',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='queued', max_length=16),
        ),
    ]
