# Generated by Django 5.2.16 on 2026-07-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_engine', '0005_email_tracking_compliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundemail',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed'), ('quota', 'Quota exceeded')], default='queued', max_length=16),
        ),
    ]
